name: Template Validation Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  template_validation_job:
    runs-on: ubuntu-latest
    name: template validation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Template
        uses: microsoft/template-validation-action@Latest
        with:
          validateAzd: true
          useDevContainer: false
        id: validation
        env:
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Project-specific variables (matches azure-dev.yaml/azure.yaml/main.parameters.json)
          # Release Manager specific variables
          # Azure AI Foundry Settings
          AZURE_AI_FOUNDRY_RESOURCE_NAME: ${{ vars.AZURE_AI_FOUNDRY_RESOURCE_NAME }}
          AZURE_AI_FOUNDRY_PROJECT_NAME: ${{ vars.AZURE_AI_FOUNDRY_PROJECT_NAME }}
          AZURE_AI_MODEL_DEPLOYMENT_NAME: ${{ vars.AZURE_AI_MODEL_DEPLOYMENT_NAME }}

          # Azure OpenAI Settings
          AZURE_OPENAI_ENDPOINT: ${{ vars.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_RESPONSES_DEPLOYMENT_NAME: ${{ vars.AZURE_OPENAI_RESPONSES_DEPLOYMENT_NAME }}
          AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME: ${{ vars.AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME }}

          # Azure Content Safety Service Settings
          AZURE_CONTENT_SAFETY_RESOURCE_NAME: ${{ vars.AZURE_CONTENT_SAFETY_RESOURCE_NAME }}

          # JIRA Configuration
          JIRA_SERVER_ENDPOINT: ${{ vars.JIRA_SERVER_ENDPOINT }}
          JIRA_SERVER_USERNAME: ${{ vars.JIRA_SERVER_USERNAME }}
          JIRA_SERVER_PASSWORD: ${{ secrets.JIRA_SERVER_PASSWORD }}

          # Azure DevOps Configuration
          AZURE_DEVOPS_ORG_NAME: ${{ secrets.AZURE_DEVOPS_ORG_NAME }}
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_EXT_PAT }}

      - name: print result
        run: cat ${{ steps.validation.outputs.resultFile }}
